MODEL:
  META_ARCHITECTURE: "Detr"
  BACKBONE:
    NAME: "build_two_stem_resnet_backbone"
  WEIGHTS: "checkpoints/torchvision-R-50_double_stems.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  DETR:
    GIOU_WEIGHT: 2.0
    L1_WEIGHT: 5.0
    NUM_OBJECT_QUERIES: 100
    NUM_CLASSES: 1
    ENC_LAYERS: 6
    DEC_LAYERS: 6
    INDEX_FEEDFORWARD: -1 # res5
DATASETS:
  TRAIN: ("CrowdHuman_train",)
  TEST: ("CrowdHuman_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  STEPS: (240000,)
  MAX_ITER: 360000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 1000
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.1
    NORM_TYPE: 2.0
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  FORMAT: "RGB"  # --> 默认是bgr.
  ZIP_READ: True
TEST:
  EVAL_PERIOD: 20000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 16
VERSION: 2
