MODEL:
  META_ARCHITECTURE: "SOD"
  MASK_ON: False
  BACKBONE:
    NAME: "build_sod_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  SOD:
    USE_BASE: False
    PE_ON: False
    WITH_COORD: False
    CENTER_SYMMETRY: False
    SCALE_VARIANCE: False
    LOC_PRIOR: False
    SCALE_NORMALIZE: False
    CIOU_ON: False
    RESCALE_FIRST: True
    MAX_POOL: False
    TYPE_ATTENTION: "softmax"
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
