_BASE_: "../Base-SOLOv2.yaml"
MODEL:
  META_ARCHITECTURE: "SOLOv2_EDGE"
  WEIGHTS: "models/R-50.pkl"
  RESNETS:
    DEPTH: 50
  SOLOV2:
    NUM_INSTANCE_CONVS: 4
    USE_DCN_IN_INSTANCE: False
    FLAG_EDGE: True
SOLVER:
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 8
INPUT:
  MIN_SIZE_TRAIN: (800,)
DATASETS:
  TRAIN: ("coco_2017_val",)

