_BASE_: "../Base-SOLOv2.yaml"
MODEL:
  WEIGHTS: "models/R-50.pkl"
  RESNETS:
    DEPTH: 50
  SOLOV2:
    NUM_INSTANCE_CONVS: 4
    USE_DCN_IN_INSTANCE: False
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 500
  STEPS: (210000, 250000)
  MAX_ITER: 270000
