_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "models/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  # Appended by Rufeng Zhang.
  ROI_HEADS:
    NAME: "SemiStandardROIHeads"
  # ROI_MASK_HEAD:
  #   NAME: "SemiMaskRCNNConvUpsampleHead"
DATASETS:
  TRAIN: ("instances_train2017_semi_0.1_min_200",)
  TEST: ("coco_2017_train",)
# TEST:
#  AUG:
#    ENABLED: True
#    FLIP: True
