_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "models/faster_rcnn.pth" # "models/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  # Appended by Rufeng Zhang.
  ROI_HEADS:
    NAME: "SemiStandardROIHeads"
  ROI_MASK_HEAD:
    NAME: "SemiMaskRCNNConvUpsampleHead"
  FLAG_SEMI: True
  # FLAG_SEMI_ON_LOSS: True
  FREEZE_FASTER_RCNN: False
  COEFF_SEMI: 0.1
DATASETS:
  TRAIN: ("instances_val2017_semi_0.1_min_200",)
  TEST: ("coco_2017_val",)
